### ISSUE TITLE
AppBar as PrefferedSizeWidget

### ISSUE THREAD

**Issue by pietrolimperio** [shiburagi/Drawer-Behavior-Flutter#44]
Hi, I'm using your package (so thanks first of all for your work!).

I'm currently working on the responsiveness of my application and I noticed that the appBar attribute in DrawerScaffold is of the type AppBar differently from the material Scaffold that is PrefferedSizeWidget and allow to resize the height of the app bar for different device. Do you think is it possible to fix it?

**Comment by shiburagi** [comment]
This issue should be resolved on version 2.1.1

**Comment by pietrolimperio** [comment]
Thanks for your feedback, but I think you forgot the toolbarHeight attribute that was the one I added in my fork to have a better responsiveness on different devices
